development:
  adapter: mysql2
  database: 'clouds-dev'
  username: 'clouds'
  password: 'cL0wDz.'

test:
  adapter: mysql2
  database: 'clouds-test'
  username: 'clouds'
  password: 'cL0wDz.'

production:
  adapter: mysql2
  database: 'clouds'
  username: 'clouds'
  password: 'cL0wDz.'
